import { createHash, randomBytes } from "node:crypto";
import {
	chmodSync,
	existsSync,
	lstatSync,
	mkdirSync,
	readFileSync,
	readdirSync,
	renameSync,
	rmSync,
	statSync,
	writeFileSync,
} from "node:fs";
import { basename, isAbsolute, relative, resolve, sep } from "node:path";

import { S11tDiagnosticError, type S11tDiagnostic } from "../diagnostics.js";
import { resolvesWithin } from "../path-safety.js";
import {
	OPERATION_ID_PATTERN,
	parseMigrationManifest,
	type MigrationManifest,
	type MigrationOperation,
	type MigrationSummary,
} from "./journal-manifest.js";

export type {
	MigrationManifest,
	MigrationMapping,
	MigrationOperation,
	MigrationSummary,
} from "./journal-manifest.js";

const IGNORE_CONTENT = "# Generated by S11t. Migration backups may contain source content.\n*\n!.gitignore\n";
const PREPARING_DIRECTORY_PATTERN = /^\.preparing-authoring-v2-[0-9a-f]{24}$/;

function diagnostic(
	message: string,
	file: string,
	path: Array<string | number> = [],
	code = "S11T_AUTHORING_MIGRATION_INVALID",
): never {
	const value: S11tDiagnostic = { code, severity: "error", message, file, path };
	throw new S11tDiagnosticError([value]);
}

function compareCodeUnits(left: string, right: string): number {
	return left < right ? -1 : left > right ? 1 : 0;
}

function comparePaths(left: string, right: string): number {
	return compareCodeUnits(left.replaceAll("\\", "/"), right.replaceAll("\\", "/"));
}

function sha256(bytes: string): string {
	return `sha256:${createHash("sha256").update(bytes).digest("hex")}`;
}

function migrationRoot(configDirectory: string): string {
	const root = resolve(configDirectory, ".s11t/migrations");
	if (!resolvesWithin(configDirectory, root)) {
		return diagnostic("Migration backup directory resolves outside the config directory", root);
	}
	return root;
}

function operationDirectory(configDirectory: string, operationId: string): string {
	if (!OPERATION_ID_PATTERN.test(operationId)) {
		return diagnostic("Invalid migration operation ID", "s11t.config.toml", ["operationId"]);
	}
	const directory = resolve(migrationRoot(configDirectory), operationId);
	if (existsSync(directory) && !resolvesWithin(configDirectory, directory)) {
		return diagnostic("Migration operation directory resolves outside the config directory", directory);
	}
	return directory;
}

function relativeMigrationPath(configDirectory: string, path: string): string {
	const result = relative(configDirectory, path);
	if (result === "" || isAbsolute(result) || result === ".." || result.startsWith(`..${sep}`)) {
		return diagnostic("Migration target escapes the config directory", path);
	}
	return result.replaceAll("\\", "/");
}

export function atomicWrite(path: string, bytes: string, requestedMode?: number): void {
	if (existsSync(path) && lstatSync(path).isSymbolicLink()) {
		return diagnostic("Migration write target must not be a symbolic link", path);
	}
	const mode =
		requestedMode ?? (existsSync(path) ? statSync(path).mode & 0o777 : 0o644);
	const temporary = resolve(path, `../.${basename(path)}.${process.pid}.${randomBytes(8).toString("hex")}.tmp`);
	try {
		writeFileSync(temporary, bytes, { encoding: "utf8", flag: "wx", mode });
		chmodSync(temporary, mode);
		renameSync(temporary, path);
	} finally {
		rmSync(temporary, { force: true });
	}
}

function removeStalePreparingDirectories(configDirectory: string): void {
	const root = migrationRoot(configDirectory);
	if (!existsSync(root)) return;
	for (const entry of readdirSync(root, { withFileTypes: true })) {
		if (!PREPARING_DIRECTORY_PATTERN.test(entry.name)) continue;
		if (!entry.isDirectory()) {
			return diagnostic("Migration preparation entry must be a directory", resolve(root, entry.name));
		}
		const directory = resolve(root, entry.name);
		if (!resolvesWithin(configDirectory, directory)) {
			return diagnostic("Migration preparation directory resolves outside the config directory", directory);
		}
		rmSync(directory, { recursive: true, force: true });
	}
}

function ensureIgnored(configDirectory: string): void {
	const root = migrationRoot(configDirectory);
	mkdirSync(root, { recursive: true, mode: 0o700 });
	const ignorePath = resolve(root, ".gitignore");
	if (!resolvesWithin(configDirectory, ignorePath)) {
		return diagnostic("Migration ignore file resolves outside the config directory", ignorePath);
	}
	if (!existsSync(ignorePath) || readFileSync(ignorePath, "utf8") !== IGNORE_CONTENT) {
		atomicWrite(ignorePath, IGNORE_CONTENT, 0o600);
	}
}

export function readMigrationManifest(
	configDirectory: string,
	operationId: string,
): MigrationManifest {
	const directory = operationDirectory(configDirectory, operationId);
	const manifestPath = resolve(directory, "manifest.json");
	let input: unknown;
	try {
		if (lstatSync(manifestPath).isSymbolicLink()) {
			return diagnostic("Migration manifest must not be a symbolic link", manifestPath);
		}
		input = JSON.parse(readFileSync(manifestPath, "utf8"));
	} catch (error) {
		if (error instanceof S11tDiagnosticError) throw error;
		const message = error instanceof Error ? error.message : String(error);
		return diagnostic(`Unable to read migration manifest: ${message}`, manifestPath);
	}
	const manifest = parseMigrationManifest(input, manifestPath);
	if (manifest.operationId !== operationId) {
		return diagnostic(
			"Migration manifest operation ID does not match its directory",
			manifestPath,
			["operationId"],
		);
	}
	return manifest;
}

export function writeMigrationManifest(
	configDirectory: string,
	manifest: MigrationManifest,
): void {
	const path = resolve(operationDirectory(configDirectory, manifest.operationId), "manifest.json");
	atomicWrite(path, `${JSON.stringify(manifest, null, 2)}\n`, 0o600);
}

export function pendingMigration(configDirectory: string): string | undefined {
	const root = migrationRoot(configDirectory);
	if (!existsSync(root)) return undefined;
	for (const entry of readdirSync(root, { withFileTypes: true }).sort((left, right) =>
		compareCodeUnits(left.name, right.name),
	)) {
		if (!entry.isDirectory() || !OPERATION_ID_PATTERN.test(entry.name)) continue;
		const manifest = readMigrationManifest(configDirectory, entry.name);
		if (manifest.state === "prepared") return entry.name;
	}
	return undefined;
}

export function prepareMigration(
	configDirectory: string,
	configPath: string,
	writes: ReadonlyMap<string, string>,
	summary: MigrationSummary,
): MigrationManifest {
	const operationId = `authoring-v2-${randomBytes(12).toString("hex")}`;
	ensureIgnored(configDirectory);
	removeStalePreparingDirectories(configDirectory);
	const root = migrationRoot(configDirectory);
	const preparingDirectory = resolve(root, `.preparing-${operationId}`);
	const preparedDirectory = operationDirectory(configDirectory, operationId);
	mkdirSync(preparingDirectory, { recursive: false, mode: 0o700 });
	try {
		const files = [...writes.entries()]
			.sort(([left], [right]) => comparePaths(left, right))
			.map(([path, afterBytes], index) => {
				if (lstatSync(path).isSymbolicLink()) {
					return diagnostic("Migration target must not be a symbolic link", path);
				}
				const beforeBytes = readFileSync(path, "utf8");
				const backup = `${String(index).padStart(4, "0")}.bak`;
				const mode = statSync(path).mode & 0o777;
				writeFileSync(resolve(preparingDirectory, backup), beforeBytes, {
					encoding: "utf8",
					flag: "wx",
					mode: 0o600,
				});
				return {
					path: relativeMigrationPath(configDirectory, path),
					backup,
					beforeSha256: sha256(beforeBytes),
					afterSha256: sha256(afterBytes),
					mode,
				};
			});
		const manifest: MigrationManifest = {
			schemaVersion: 1,
			operation: "authoring-v2",
			operationId,
			state: "prepared",
			createdAt: new Date().toISOString(),
			configPath: relativeMigrationPath(configDirectory, configPath),
			summary,
			files,
		};
		writeFileSync(
			resolve(preparingDirectory, "manifest.json"),
			`${JSON.stringify(manifest, null, 2)}\n`,
			{ encoding: "utf8", flag: "wx", mode: 0o600 },
		);
		renameSync(preparingDirectory, preparedDirectory);
		return manifest;
	} catch (error) {
		rmSync(preparingDirectory, { recursive: true, force: true });
		throw error;
	}
}

export function restoreMigrationFiles(
	configDirectory: string,
	manifest: MigrationManifest,
): void {
	const directory = operationDirectory(configDirectory, manifest.operationId);
	const restorePlan = manifest.files.map((entry) => {
		const path = resolve(configDirectory, entry.path);
		if (
			relativeMigrationPath(configDirectory, path) !== entry.path ||
			!resolvesWithin(configDirectory, path)
		) {
			return diagnostic(
				"Migration manifest contains a non-canonical target path",
				resolve(directory, "manifest.json"),
				["files", entry.path],
			);
		}
		const backupPath = resolve(directory, entry.backup);
		if (!resolvesWithin(configDirectory, backupPath)) {
			return diagnostic("Migration backup resolves outside the config directory", backupPath);
		}
		if (lstatSync(path).isSymbolicLink()) {
			return diagnostic("Migration target must not be a symbolic link", path);
		}
		if (lstatSync(backupPath).isSymbolicLink()) {
			return diagnostic("Migration backup must not be a symbolic link", backupPath);
		}
		const bytes = readFileSync(backupPath, "utf8");
		if (sha256(bytes) !== entry.beforeSha256) {
			return diagnostic("Migration backup checksum mismatch", backupPath);
		}
		const current = readFileSync(path, "utf8");
		const currentSha256 = sha256(current);
		if (currentSha256 !== entry.beforeSha256 && currentSha256 !== entry.afterSha256) {
			return diagnostic(
				"Migration target changed after the operation; refusing to overwrite it",
				path,
				[],
				"S11T_AUTHORING_MIGRATION_DRIFT",
			);
		}
		return { path, bytes, beforeSha256: entry.beforeSha256, mode: entry.mode };
	});
	for (const entry of restorePlan) atomicWrite(entry.path, entry.bytes, entry.mode);
	for (const entry of restorePlan) {
		if (sha256(readFileSync(entry.path, "utf8")) !== entry.beforeSha256) {
			throw new Error(`Migration restore verification failed for ${entry.path}`);
		}
		if (
			entry.mode !== undefined &&
			process.platform !== "win32" &&
			(statSync(entry.path).mode & 0o777) !== entry.mode
		) {
			throw new Error(`Migration restore mode verification failed for ${entry.path}`);
		}
	}
}

export function listMigrations(configDirectory: string): MigrationOperation[] {
	const root = migrationRoot(configDirectory);
	if (!existsSync(root)) return [];
	return readdirSync(root, { withFileTypes: true })
		.filter((entry) => entry.isDirectory() && OPERATION_ID_PATTERN.test(entry.name))
		.map((entry) => readMigrationManifest(configDirectory, entry.name))
		.sort(
			(left, right) =>
				compareCodeUnits(left.createdAt ?? "", right.createdAt ?? "") ||
				compareCodeUnits(left.operationId, right.operationId),
		)
		.map(({ operationId, state, createdAt, configPath, summary }) => ({
			operationId,
			state,
			...(createdAt === undefined ? {} : { createdAt }),
			configPath,
			summary,
		}));
}

export function purgeMigration(
	configDirectory: string,
	operationId: string,
	expectedConfigPath?: string,
): MigrationOperation {
	const manifest = readMigrationManifest(configDirectory, operationId);
	if (expectedConfigPath !== undefined && manifest.configPath !== expectedConfigPath) {
		return diagnostic(
			"Migration manifest belongs to a different config",
			resolve(operationDirectory(configDirectory, operationId), "manifest.json"),
			["configPath"],
		);
	}
	if (manifest.state === "prepared") {
		return diagnostic(
			"Prepared migration must be restored before it can be purged",
			resolve(operationDirectory(configDirectory, operationId), "manifest.json"),
			["state"],
			"S11T_AUTHORING_MIGRATION_PENDING",
		);
	}
	const result: MigrationOperation = {
		operationId: manifest.operationId,
		state: manifest.state,
		...(manifest.createdAt === undefined ? {} : { createdAt: manifest.createdAt }),
		configPath: manifest.configPath,
		summary: manifest.summary,
	};
	rmSync(operationDirectory(configDirectory, operationId), { recursive: true, force: true });
	return result;
}
