// Generated by s11tnext-cli. Do not edit.
// compilerVersion: 0.0.0
// catalogDigest: sha256:c5e95698f07f385816bf04f2ac76f12f117a4b04726b1ad3cf9f95a4458f7b93

import type { CatalogContract } from "s11tnext";
import { createCatalog } from "s11tnext";

export const expectedCatalogDigest = "sha256:c5e95698f07f385816bf04f2ac76f12f117a4b04726b1ad3cf9f95a4458f7b93" as const;

export type SystemContextKey =
	| "codingAgent.identity";

export type SystemContextValueMap = {
	"codingAgent.identity": {
		"taskGoal": string;
	};
};

export type SystemContextOutputMap = {
	"codingAgent.identity": "text";
};

export type AppCatalogContract = CatalogContract<
	SystemContextKey,
	SystemContextValueMap,
	SystemContextOutputMap
>;

export function createAppCatalog(artifact: unknown) {
	return createCatalog<AppCatalogContract>(artifact, { expectedCatalogDigest });
}
