import { COMPILER_VERSION } from "@s11t/runtime/compiler";
import type {
	S11tCatalogArtifactV1,
	S11tCatalogArtifactV2,
	S11tCatalogArtifactV3,
	S11tCompiledContextV1,
	S11tCompiledContextV2,
} from "@s11t/runtime";

function compareCodeUnits(left: string, right: string): number {
	return left < right ? -1 : left > right ? 1 : 0;
}

function typeFor(variable: S11tCompiledContextV1["variables"][string]): string {
	if (variable.type === "json") return "JsonValue";
	return variable.type;
}

function emitTypesV1(artifact: S11tCatalogArtifactV1): string {
	const keys = Object.keys(artifact.contexts).sort(compareCodeUnits);
	const usesJson = Object.values(artifact.contexts).some((context) =>
		Object.values(context.variables).some((variable) => variable.type === "json"),
	);
	const keyUnion = keys.map((key) => `\t| ${JSON.stringify(key)}`).join("\n");
	const values = keys
		.map((key) => {
			const context = artifact.contexts[key]!;
			const fields = Object.keys(context.variables)
				.sort(compareCodeUnits)
				.map((name) => `\t\t${JSON.stringify(name)}: ${typeFor(context.variables[name]!)};`)
				.join("\n");
			return `\t${JSON.stringify(key)}: {${fields.length === 0 ? "" : `\n${fields}\n\t`}};`;
		})
		.join("\n");
	const outputs = keys.map((key) => `\t${JSON.stringify(key)}: "text";`).join("\n");
	return `// Generated by @s11t/cli. Do not edit.\n// compilerVersion: ${COMPILER_VERSION}\n// catalogDigest: ${artifact.catalogDigest}\n\nimport type { CatalogContract${usesJson ? ", JsonValue" : ""} } from "@s11t/runtime";\nimport { createCatalog } from "@s11t/runtime";\n\nexport const expectedCatalogDigest = ${JSON.stringify(artifact.catalogDigest)} as const;\n\nexport type SystemContextKey =\n${keyUnion};\n\nexport type SystemContextValueMap = {\n${values}\n};\n\nexport type SystemContextOutputMap = {\n${outputs}\n};\n\nexport type AppCatalogContract = CatalogContract<\n\tSystemContextKey,\n\tSystemContextValueMap,\n\tSystemContextOutputMap\n>;\n\nexport function createAppCatalog(artifact: unknown) {\n\treturn createCatalog<AppCatalogContract>(artifact, { expectedCatalogDigest });\n}\n`;
}

function typeForV2(variable: S11tCompiledContextV2["variables"][string]): string {
	if (variable.type === "json") return "JsonValue";
	return variable.type;
}

function fieldsForV2(context: S11tCompiledContextV2): string {
	return Object.keys(context.variables)
		.sort(compareCodeUnits)
		.map((name) => `\t\t${JSON.stringify(name)}: ${typeForV2(context.variables[name]!)};`)
		.join("\n");
}

function emitTypesV2(artifact: S11tCatalogArtifactV2 | S11tCatalogArtifactV3): string {
	const canonicalKeys = Object.keys(artifact.contexts).sort(compareCodeUnits);
	const usesJson = Object.values(artifact.contexts).some((context) =>
		Object.values(context.variables).some((variable) => variable.type === "json"),
	);
	const legacyKeys = Object.keys(artifact.aliases).sort(compareCodeUnits);
	const canonicalUnion = canonicalKeys.map((key) => `\t| ${JSON.stringify(key)}`).join("\n");
	const legacyUnion = legacyKeys.map((key) => `\t| ${JSON.stringify(key)}`).join("\n");
	const allKeys = [...canonicalKeys, ...legacyKeys].sort(compareCodeUnits);
	const values = allKeys
		.map((key) => {
			const canonical = artifact.aliases[key] ?? key;
			const context = artifact.contexts[canonical]!;
			const fields = fieldsForV2(context);
			return fields.length === 0
				? `\t${JSON.stringify(key)}: Record<string, never>;`
				: `\t${JSON.stringify(key)}: {\n${fields}\n\t};`;
		})
		.join("\n");
	const outputs = allKeys.map((key) => `\t${JSON.stringify(key)}: "text";`).join("\n");
	const factory = artifact.schemaVersion === 3 ? "createCatalogV3" : "createCatalogV2";
	return `// Generated by @s11t/cli. Do not edit.\n// compilerVersion: ${COMPILER_VERSION}\n// catalogDigest: ${artifact.catalogDigest}\n\nimport type { CatalogContract${usesJson ? ", JsonValue" : ""} } from "@s11t/runtime";\nimport { ${factory} } from "@s11t/runtime";\n\nexport const expectedCatalogDigest = ${JSON.stringify(artifact.catalogDigest)} as const;\n\nexport type CanonicalSystemContextKey =\n${canonicalUnion};\n\n/** @deprecated Migrate callers to CanonicalSystemContextKey. */\nexport type LegacySystemContextKey =\n${legacyUnion.length === 0 ? "\tnever" : legacyUnion};\n\nexport type SystemContextKey = CanonicalSystemContextKey | LegacySystemContextKey;\n\nexport type SystemContextValueMap = {\n${values}\n};\n\nexport type SystemContextOutputMap = {\n${outputs}\n};\n\nexport type AppCatalogContract = CatalogContract<\n\tSystemContextKey,\n\tSystemContextValueMap,\n\tSystemContextOutputMap\n>;\n\nexport function createAppCatalog(artifact: unknown) {\n\treturn ${factory}<AppCatalogContract>(artifact, { expectedCatalogDigest });\n}\n`;
}

export function emitTypes(
	artifact: S11tCatalogArtifactV1 | S11tCatalogArtifactV2 | S11tCatalogArtifactV3,
): string {
	return artifact.schemaVersion === 1 ? emitTypesV1(artifact) : emitTypesV2(artifact);
}
