import { COMPILER_VERSION } from "@s11t/runtime/compiler";
import type { S11tCatalogArtifact, S11tCompiledContext } from "@s11t/runtime";

function compareCodeUnits(left: string, right: string): number {
	return left < right ? -1 : left > right ? 1 : 0;
}

function typeFor(variable: S11tCompiledContext["variables"][string]): string {
	if (variable.type === "json") return "JsonValue";
	return variable.type;
}

function fieldsFor(context: S11tCompiledContext): string {
	return Object.keys(context.variables)
		.sort(compareCodeUnits)
		.map((name) => `\t\t${JSON.stringify(name)}: ${typeFor(context.variables[name]!)};`)
		.join("\n");
}

export function emitTypes(artifact: S11tCatalogArtifact): string {
	const canonicalKeys = Object.keys(artifact.contexts).sort(compareCodeUnits);
	const aliasKeys = Object.keys(artifact.aliases).sort(compareCodeUnits);
	const allKeys = [...canonicalKeys, ...aliasKeys].sort(compareCodeUnits);
	const usesJson = Object.values(artifact.contexts).some((context) =>
		Object.values(context.variables).some((variable) => variable.type === "json"),
	);
	const canonicalUnion = canonicalKeys.map((key) => `\t| ${JSON.stringify(key)}`).join("\n");
	const aliasUnion = aliasKeys.map((key) => `\t| ${JSON.stringify(key)}`).join("\n");
	const values = allKeys
		.map((key) => {
			const canonical = artifact.aliases[key] ?? key;
			const context = artifact.contexts[canonical]!;
			const fields = fieldsFor(context);
			return fields.length === 0
				? `\t${JSON.stringify(key)}: Record<string, never>;`
				: `\t${JSON.stringify(key)}: {\n${fields}\n\t};`;
		})
		.join("\n");
	const outputs = allKeys.map((key) => `\t${JSON.stringify(key)}: "text";`).join("\n");
	return `// Generated by @s11t/cli. Do not edit.\n// compilerVersion: ${COMPILER_VERSION}\n// catalogDigest: ${artifact.catalogDigest}\n\nimport type { CatalogContract${usesJson ? ", JsonValue" : ""} } from "@s11t/runtime";\nimport { createCatalog } from "@s11t/runtime";\n\nexport const expectedCatalogDigest = ${JSON.stringify(artifact.catalogDigest)} as const;\n\nexport type CanonicalSystemContextKey =\n${canonicalUnion};\n\nexport type SystemContextAlias =\n${aliasUnion.length === 0 ? "\tnever" : aliasUnion};\n\nexport type SystemContextKey = CanonicalSystemContextKey | SystemContextAlias;\n\nexport type SystemContextValueMap = {\n${values}\n};\n\nexport type SystemContextOutputMap = {\n${outputs}\n};\n\nexport type AppCatalogContract = CatalogContract<\n\tSystemContextKey,\n\tSystemContextValueMap,\n\tSystemContextOutputMap\n>;\n\nexport function createAppCatalog(artifact: unknown) {\n\treturn createCatalog<AppCatalogContract>(artifact, { expectedCatalogDigest });\n}\n`;
}
