import { COMPILER_VERSION } from "s11tnext/compiler";
import type { S11tnextCatalogArtifact, S11tnextCompiledContext } from "s11tnext";

function compareCodeUnits(left: string, right: string): number {
	return left < right ? -1 : left > right ? 1 : 0;
}

function typeFor(variable: S11tnextCompiledContext["variables"][string]): string {
	if (variable.type === "json") return "JsonValue";
	return variable.type;
}

function fieldsFor(context: S11tnextCompiledContext): string {
	return Object.keys(context.variables)
		.sort(compareCodeUnits)
		.map((name) => `\t\t${JSON.stringify(name)}: ${typeFor(context.variables[name]!)};`)
		.join("\n");
}

export function emitTypes(artifact: S11tnextCatalogArtifact): string {
	const canonicalKeys = Object.keys(artifact.contexts).sort(compareCodeUnits);
	const usesJson = Object.values(artifact.contexts).some((context) =>
		Object.values(context.variables).some((variable) => variable.type === "json"),
	);
	const keyUnion = canonicalKeys.map((key) => `\t| ${JSON.stringify(key)}`).join("\n");
	const values = canonicalKeys
		.map((key) => {
			const context = artifact.contexts[key]!;
			const fields = fieldsFor(context);
			return fields.length === 0
				? `\t${JSON.stringify(key)}: Record<string, never>;`
				: `\t${JSON.stringify(key)}: {\n${fields}\n\t};`;
		})
		.join("\n");
	const outputs = canonicalKeys.map((key) => `\t${JSON.stringify(key)}: "text";`).join("\n");
	return `// Generated by s11tnext-cli. Do not edit.\n// compilerVersion: ${COMPILER_VERSION}\n// catalogDigest: ${artifact.catalogDigest}\n\nimport type { CatalogContract${usesJson ? ", JsonValue" : ""} } from "s11tnext";\nimport { createCatalog } from "s11tnext";\n\nexport const expectedCatalogDigest = ${JSON.stringify(artifact.catalogDigest)} as const;\n\nexport type SystemContextKey =\n${keyUnion};\n\nexport type SystemContextValueMap = {\n${values}\n};\n\nexport type SystemContextOutputMap = {\n${outputs}\n};\n\nexport type AppCatalogContract = CatalogContract<\n\tSystemContextKey,\n\tSystemContextValueMap,\n\tSystemContextOutputMap\n>;\n\nexport function createAppCatalog(artifact: unknown) {\n\treturn createCatalog<AppCatalogContract>(artifact, { expectedCatalogDigest });\n}\n`;
}
