// Generated by @s11t/cli. Do not edit.
// compilerVersion: 0.0.0
// catalogDigest: sha256:c0a461dcfe599f669eb5ba6cb1c640be4a3b4c90552eac0dad213beab1f843fb

import type { CatalogContract } from "@s11t/runtime";
import { createCatalog } from "@s11t/runtime";

export const expectedCatalogDigest = "sha256:c0a461dcfe599f669eb5ba6cb1c640be4a3b4c90552eac0dad213beab1f843fb" as const;

export type SystemContextKey =
	| "codingAgent.identity";

export type SystemContextValueMap = {
	"codingAgent.identity": {
		"taskGoal": string;
	};
};

export type SystemContextOutputMap = {
	"codingAgent.identity": "text";
};

export type AppCatalogContract = CatalogContract<
	SystemContextKey,
	SystemContextValueMap,
	SystemContextOutputMap
>;

export function createAppCatalog(artifact: unknown) {
	return createCatalog<AppCatalogContract>(artifact, { expectedCatalogDigest });
}
