// Generated by @s11t/cli. Do not edit.
// compilerVersion: 0.0.0
// catalogDigest: sha256:9beacfd1b67bc08ef77e7440001837a79b6c127d3013cc25a8a3fd1fb8e9992f

import type { CatalogContract, JsonValue } from "@s11t/runtime";
import { createCatalog } from "@s11t/runtime";

export const expectedCatalogDigest = "sha256:9beacfd1b67bc08ef77e7440001837a79b6c127d3013cc25a8a3fd1fb8e9992f" as const;

export type SystemContextKey =
	| "codingAgent:identity";

export type SystemContextValueMap = {
	"codingAgent:identity": {
		"taskGoal": string;
	};
};

export type SystemContextOutputMap = {
	"codingAgent:identity": "text";
};

export type AppCatalogContract = CatalogContract<
	SystemContextKey,
	SystemContextValueMap,
	SystemContextOutputMap
>;

export function createAppCatalog(artifact: unknown) {
	return createCatalog<AppCatalogContract>(artifact, { expectedCatalogDigest });
}
