// Generated by @s11t/cli. Do not edit.
// compilerVersion: 0.0.0
// catalogDigest: sha256:ad4e6a820aa13c9402b5d8c8fa2b6b2380dd2d9be5d27c8f6a5cf9b54d1a3479

import type { CatalogContract } from "@s11t/runtime";
import { createCatalog } from "@s11t/runtime";

export const expectedCatalogDigest = "sha256:ad4e6a820aa13c9402b5d8c8fa2b6b2380dd2d9be5d27c8f6a5cf9b54d1a3479" as const;

export type CanonicalSystemContextKey =
	| "codingAgent.identity";

export type SystemContextAlias =
	never;

export type SystemContextKey = CanonicalSystemContextKey | SystemContextAlias;

export type SystemContextValueMap = {
	"codingAgent.identity": {
		"taskGoal": string;
	};
};

export type SystemContextOutputMap = {
	"codingAgent.identity": "text";
};

export type AppCatalogContract = CatalogContract<
	SystemContextKey,
	SystemContextValueMap,
	SystemContextOutputMap
>;

export function createAppCatalog(artifact: unknown) {
	return createCatalog<AppCatalogContract>(artifact, { expectedCatalogDigest });
}
